ForceOfHell: ForceOfHell.Scripts.StateMachine.MovementStateMachine.State Class Reference
ForceOfHell.Scripts.StateMachine.MovementStateMachine.State Class Reference
Clase base para todos los estados de la máquina de movimiento. Contiene los métodos ciclo de vida que deben implementar los estados concretos.
Public Member Functions
virtual void Enter ()
Se invoca cuando el estado empieza (se entra en él).
virtual void Exit ()
Se invoca cuando el estado termina (se sale de él).
virtual new System.Threading.Tasks.Task Ready ()
Se invoca una sola vez cuando se inicializa el nodo/estado. Versión asíncrona para permitir esperas (por ejemplo, espera a otros nodos).
virtual void Update (double delta)
Actualización por frame (non-physics). Delta en segundos.
virtual void UpdatePhysics (double delta)
Actualización en el paso de física (_PhysicsProcess). Delta en segundos.
virtual void HandleInput (InputEvent ev)
Procesa eventos de entrada no manejados (unhandled input).
Protected Attributes
MovementStateMachine stateMachine
Campo protegido mantenido por compatibilidad. Los estados existentes usan stateMachine.
Properties
MovementStateMachine StateMachine [get, set]
Propiedad pública para acceder a la máquina de estados. El setter es interno.
Private Attributes
MovementStateMachine _stateMachine
Referencia a la máquina de estados que contiene este estado. Se asigna desde MovementStateMachine en tiempo de preparación. Expuesta como lectura pública pero solo asignable internamente por la máquina.
Detailed Description
Clase base para todos los estados de la máquina de movimiento. Contiene los métodos ciclo de vida que deben implementar los estados concretos.
Definition at line 10 of file State.cs.
Member Function Documentation
Enter()
virtual void ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Enter () virtual
Se invoca cuando el estado empieza (se entra en él).
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.
Definition at line 38 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
Exit()
virtual void ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Exit () virtual
Se invoca cuando el estado termina (se sale de él).
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.
Definition at line 41 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
HandleInput()
virtual void ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.HandleInput (InputEvent ev) virtual
Procesa eventos de entrada no manejados (unhandled input).
Parameters
ev Evento de entrada recibido.
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.
Definition at line 57 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._UnhandledInput().
Ready()
virtual new System.Threading.Tasks.Task ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Ready () virtual
Se invoca una sola vez cuando se inicializa el nodo/estado. Versión asíncrona para permitir esperas (por ejemplo, espera a otros nodos).
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.
Definition at line 45 of file State.cs.
Update()
virtual void ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Update (double delta) virtual
Actualización por frame (non-physics). Delta en segundos.
Parameters
delta Tiempo en segundos desde el último frame.
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.
Definition at line 49 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Process().
UpdatePhysics()
virtual void ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.UpdatePhysics (double delta) virtual
Actualización en el paso de física (_PhysicsProcess). Delta en segundos.
Parameters
delta Tiempo en segundos desde la última física.
Reimplemented in ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.
Definition at line 53 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._PhysicsProcess().
Member Data Documentation
_stateMachine
MovementStateMachine ForceOfHell.Scripts.StateMachine.MovementStateMachine.State._stateMachine private
Referencia a la máquina de estados que contiene este estado. Se asigna desde MovementStateMachine en tiempo de preparación. Expuesta como lectura pública pero solo asignable internamente por la máquina.
Definition at line 17 of file State.cs.
stateMachine
MovementStateMachine ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.stateMachine protected
Campo protegido mantenido por compatibilidad. Los estados existentes usan stateMachine.
Definition at line 35 of file State.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.Update(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.UpdatePhysics().
Property Documentation
StateMachine
MovementStateMachine ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.StateMachine get set
Propiedad pública para acceder a la máquina de estados. El setter es interno.
Definition at line 22 of file State.cs.
The documentation for this class was generated from the following file:
Scripts/StateMachine/MovementStateMachine/State.cs