ForceOfHell: ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine Class Reference
ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine Class Reference
Máquina de estados para el movimiento del jugador.
Public Member Functions
override void _Ready ()
Inicialización de la máquina de estados: carga estados hijos y establece el estado inicial.
override void _Process (double delta)
Procesamiento por frame: delega al estado actual.
override void _PhysicsProcess (double delta)
Procesamiento de física: delega al estado actual.
override void _UnhandledInput (InputEvent @event)
Procesamiento de eventos de entrada: delega al estado actual.
void TransitionTo (string key)
Pide la transición a otro estado por su clave (nombre del nodo). Si la clave no existe o ya estamos en ese estado la petición se ignora.
Public Attributes
NodePath initialState
Ruta (NodePath) al estado inicial dentro de este nodo.
Private Attributes
Dictionary< string, State > _states
Mapa de estados indexado por el Node.Name de cada estado.
State _current_state
Estado actualmente activo en la máquina.
ForceOfHell.Scripts.MainCharacter.Player _player
Referencia al jugador para verificar si está muriendo.
Detailed Description
Máquina de estados para el movimiento del jugador.
Definition at line 9 of file MovementStateMachine.cs.
Member Function Documentation
_PhysicsProcess()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._PhysicsProcess (double delta)
Procesamiento de física: delega al estado actual.
Parameters
delta Delta en segundos desde el último paso de física.
Definition at line 58 of file MovementStateMachine.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._player, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.UpdatePhysics().
_Process()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Process (double delta)
Procesamiento por frame: delega al estado actual.
Parameters
delta Delta en segundos desde el último frame.
Definition at line 48 of file MovementStateMachine.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._player, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Update().
_Ready()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready ()
Inicialización de la máquina de estados: carga estados hijos y establece el estado inicial.
Definition at line 24 of file MovementStateMachine.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._player, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._states, ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Enter(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.initialState.
_UnhandledInput()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._UnhandledInput (InputEvent @ event)
Procesamiento de eventos de entrada: delega al estado actual.
Parameters
event Evento de entrada.
Returns
Si el evento fue procesado.
Definition at line 69 of file MovementStateMachine.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._player, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.HandleInput().
TransitionTo()
void ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo (string key)
Pide la transición a otro estado por su clave (nombre del nodo). Si la clave no existe o ya estamos en ese estado la petición se ignora.
Parameters
key Nombre del nodo-estado destino dentro de este nodo.
Definition at line 82 of file MovementStateMachine.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state, ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._states, ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Enter(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.Exit().
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.HandleInput(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.IdleMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.JumpingMovementState.Update(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.RunningMovementState.Update(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.FallingMovementState.UpdatePhysics().
Member Data Documentation
_current_state
State ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._current_state private
Estado actualmente activo en la máquina.
Definition at line 18 of file MovementStateMachine.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._PhysicsProcess(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Process(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._UnhandledInput(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
_player
ForceOfHell.Scripts.MainCharacter.Player ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._player private
Referencia al jugador para verificar si está muriendo.
Definition at line 21 of file MovementStateMachine.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._PhysicsProcess(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Process(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._UnhandledInput().
_states
Dictionary<string, State > ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._states private
Mapa de estados indexado por el Node.Name de cada estado.
Definition at line 15 of file MovementStateMachine.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
initialState
NodePath ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.initialState
Ruta (NodePath) al estado inicial dentro de este nodo.
Definition at line 12 of file MovementStateMachine.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine._Ready().
The documentation for this class was generated from the following file:
Scripts/StateMachine/MovementStateMachine/MovementStateMachine.cs