ForceOfHell: ForceOfHell.Scripts.MainCharacter.Player Class Reference
ForceOfHell.Scripts.MainCharacter.Player Class Reference
Represents the main player character in the game, providing movement, health and mana management, weapon handling, and animation control. Inherits from CharacterBody2D and exposes methods and properties for player actions such as jumping, attacking, and changing weapons.
Public Member Functions
delegate void InJumpingEventHandler ()
override void _Ready ()
Initializes the node when it enters the scene tree. Sets up the main weapon and sprite components, and configures the monitoring state of the area.
override void _PhysicsProcess (double delta)
Handles per-frame physics processing, including updating sprite direction, managing coyote time, updating weapon cooldowns, and processing attacks based on available mana.
void SetAnimation (string animationName)
Reproduce una animación. Ignora si el jugador está muriendo.
async Task HitAsync (int damange)
Maneja el daño recibido por el jugador.
async Task Die ()
Inicia la secuencia de muerte: bloquea acciones, reproduce animación y recarga la escena.
void ChangeWeapon (int id)
Changes the currently equipped weapon to the weapon specified by the given identifier.
void attack ()
Performs an attack using the currently equipped weapon. Melee weapons apply a visual swing, ranged weapons apply recoil and spawn a bullet. Flips sprite to face the attack direction.
int GetManaMax ()
Gets the maximum mana value for the current instance.
int GetHealthMax ()
Gets the maximum health value for the current instance.
Public Attributes
Weapons.Weapons equip_weapon
int manaActual = mana
int healthActual = health
Static Public Attributes
const float Speed = 200.0f
const float JumpVelocity = -350.0f
const float CoyoteTimeMax = 0.15f
Properties
PackedScene CargarBullet [get, set]
float CoyoteTimeCounter [get, set]
Tiempo restante para salto coyote (acceso público, modificación interna).
bool IsDying [get, set]
Indica si el jugador está en proceso de muerte.
bool CanClimb [get, set]
float ClimbAnchorX [get, set]
Ancla horizontal de la escalera actual.
Private Member Functions
void UpdateSpriteDirection ()
Updates the horizontal flip state of the sprite and its associated weapon based on the current horizontal velocity.
void UpdateCoyoteTime (float delta)
Updates the coyote time counter based on whether the character is on the ground or in the air.
void OnAreaEntered (Area2D area)
Handles logic when the specified area enters the current object.
void OnBodyEntered (Node body)
Handles the event when a body enters the node's collision area.
void HandleCollision (Node node)
Handles collision logic for the specified node, applying damage if the node is a box.
Static Private Member Functions
static bool HasShootInput ()
Checks whether any shooting input action is currently pressed.
Private Attributes
AnimatedSprite2D animatedWeapon
AnimatedSprite2D _animatedSprite
float _coyoteTimeCounter
Static Private Attributes
const float WeaponOffsetLeft = 0f
const float WeaponOffsetRight = 13f
Detailed Description
Represents the main player character in the game, providing movement, health and mana management, weapon handling, and animation control. Inherits from CharacterBody2D and exposes methods and properties for player actions such as jumping, attacking, and changing weapons.
This class manages player state and actions, including coyote time for improved jump responsiveness, signal events for player actions, and collision handling with other game entities. It is designed to be used as the central character controller in a platformer or action game, supporting both melee and ranged combat. The player can equip different weapons, respond to damage, and trigger animations based on game events.
Definition at line 20 of file Player.cs.
Member Function Documentation
_PhysicsProcess()
override void ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess (double delta)
Handles per-frame physics processing, including updating sprite direction, managing coyote time, updating weapon cooldowns, and processing attacks based on available mana.
Parameters
delta The elapsed time, in seconds, since the previous physics frame. Used to update time-dependent logic.
Definition at line 85 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player.attack(), ForceOfHell.Scripts.MainCharacter.Player.equip_weapon, ForceOfHell.Scripts.MainCharacter.Player.HasShootInput(), ForceOfHell.Scripts.MainCharacter.Player.IsDying, ForceOfHell.Scripts.MainCharacter.Player.manaActual, ForceOfHell.Scripts.MainCharacter.Player.UpdateCoyoteTime(), and ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection().
_Ready()
override void ForceOfHell.Scripts.MainCharacter.Player._Ready ()
Initializes the node when it enters the scene tree. Sets up the main weapon and sprite components, and configures the monitoring state of the area.
Definition at line 69 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, ForceOfHell.Scripts.MainCharacter.Player.equip_weapon, and ForceOfHell.Scripts.Weapons.Weapons.Weapons().
attack()
void ForceOfHell.Scripts.MainCharacter.Player.attack ()
Performs an attack using the currently equipped weapon. Melee weapons apply a visual swing, ranged weapons apply recoil and spawn a bullet. Flips sprite to face the attack direction.
Definition at line 241 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, ForceOfHell.Scripts.MainCharacter.Player.animatedWeapon, ForceOfHell.Scripts.MainCharacter.Player.CargarBullet, ForceOfHell.Scripts.MainCharacter.Player.equip_weapon, and ForceOfHell.Scripts.MainCharacter.Player.manaActual.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess().
ChangeWeapon()
void ForceOfHell.Scripts.MainCharacter.Player.ChangeWeapon (int id)
Changes the currently equipped weapon to the weapon specified by the given identifier.
If no weapon is currently assigned or the animated weapon node is missing, an error is logged and the weapon is not changed.
Parameters
id The identifier of the weapon to equip. Must correspond to a valid weapon available to the player.
Definition at line 226 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player.equip_weapon.
Die()
async Task ForceOfHell.Scripts.MainCharacter.Player.Die ()
Inicia la secuencia de muerte: bloquea acciones, reproduce animación y recarga la escena.
Definition at line 143 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, and ForceOfHell.Scripts.MainCharacter.Player.IsDying.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.HitAsync().
GetHealthMax()
int ForceOfHell.Scripts.MainCharacter.Player.GetHealthMax ()
Gets the maximum health value for the current instance.
Returns
The maximum health as an integer. The value represents the upper limit of health for this instance.
Definition at line 277 of file Player.cs.
GetManaMax()
int ForceOfHell.Scripts.MainCharacter.Player.GetManaMax ()
Gets the maximum mana value for the current instance.
Returns
The maximum amount of mana available. The value is always non-negative.
Definition at line 268 of file Player.cs.
HandleCollision()
void ForceOfHell.Scripts.MainCharacter.Player.HandleCollision (Node node) private
Handles collision logic for the specified node, applying damage if the node is a box.
Parameters
node The node involved in the collision. If the node is a box, damage will be applied.
Definition at line 316 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player.equip_weapon.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.OnAreaEntered(), and ForceOfHell.Scripts.MainCharacter.Player.OnBodyEntered().
HasShootInput()
static bool ForceOfHell.Scripts.MainCharacter.Player.HasShootInput () static private
Checks whether any shooting input action is currently pressed.
Returns
true if any shot direction is pressed; otherwise, false.
Definition at line 286 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess().
HitAsync()
async Task ForceOfHell.Scripts.MainCharacter.Player.HitAsync (int damange)
Maneja el daño recibido por el jugador.
Definition at line 115 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, ForceOfHell.Scripts.MainCharacter.Player.Die(), and ForceOfHell.Scripts.MainCharacter.Player.healthActual.
InJumpingEventHandler()
delegate void ForceOfHell.Scripts.MainCharacter.Player.InJumpingEventHandler ()
OnAreaEntered()
void ForceOfHell.Scripts.MainCharacter.Player.OnAreaEntered (Area2D area) private
Handles logic when the specified area enters the current object.
Parameters
area The area that has entered and triggered the event. Cannot be null.
Definition at line 298 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player.HandleCollision().
OnBodyEntered()
void ForceOfHell.Scripts.MainCharacter.Player.OnBodyEntered (Node body) private
Handles the event when a body enters the node's collision area.
Parameters
body The node representing the body that has entered the collision area. Cannot be null.
Definition at line 307 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player.HandleCollision().
SetAnimation()
void ForceOfHell.Scripts.MainCharacter.Player.SetAnimation (string animationName)
Reproduce una animación. Ignora si el jugador está muriendo.
Definition at line 106 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, and ForceOfHell.Scripts.MainCharacter.Player.IsDying.
UpdateCoyoteTime()
void ForceOfHell.Scripts.MainCharacter.Player.UpdateCoyoteTime (float delta) private
Updates the coyote time counter based on whether the character is on the ground or in the air.
Coyote time allows the character to jump for a brief period after leaving the ground, improving responsiveness in platforming controls.
Parameters
delta The elapsed time, in seconds, since the last update. Must be non-negative.
Definition at line 212 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._coyoteTimeCounter, and ForceOfHell.Scripts.MainCharacter.Player.CoyoteTimeMax.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess().
UpdateSpriteDirection()
void ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection () private
Updates the horizontal flip state of the sprite and its associated weapon based on the current horizontal velocity.
This method ensures that the sprite and weapon visually face the correct direction according to movement. If the direction has not changed since the last update, no changes are made. The weapon's position is also adjusted to match the new orientation.
Definition at line 177 of file Player.cs.
References ForceOfHell.Scripts.MainCharacter.Player._animatedSprite, ForceOfHell.Scripts.MainCharacter.Player.animatedWeapon, ForceOfHell.Scripts.MainCharacter.Player.WeaponOffsetLeft, and ForceOfHell.Scripts.MainCharacter.Player.WeaponOffsetRight.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess().
Member Data Documentation
_animatedSprite
AnimatedSprite2D ForceOfHell.Scripts.MainCharacter.Player._animatedSprite private
Definition at line 48 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._Ready(), ForceOfHell.Scripts.MainCharacter.Player.attack(), ForceOfHell.Scripts.MainCharacter.Player.Die(), ForceOfHell.Scripts.MainCharacter.Player.HitAsync(), ForceOfHell.Scripts.MainCharacter.Player.SetAnimation(), and ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection().
_coyoteTimeCounter
float ForceOfHell.Scripts.MainCharacter.Player._coyoteTimeCounter private
Definition at line 49 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.UpdateCoyoteTime().
animatedWeapon
AnimatedSprite2D ForceOfHell.Scripts.MainCharacter.Player.animatedWeapon private
Definition at line 38 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.attack(), and ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection().
CoyoteTimeMax
const float ForceOfHell.Scripts.MainCharacter.Player.CoyoteTimeMax = 0.15f static
Definition at line 24 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.UpdateCoyoteTime().
equip_weapon
Weapons.Weapons ForceOfHell.Scripts.MainCharacter.Player.equip_weapon
Definition at line 30 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess(), ForceOfHell.Scripts.MainCharacter.Player._Ready(), ForceOfHell.Scripts.MainCharacter.Player.attack(), ForceOfHell.Scripts.MainCharacter.Player.ChangeWeapon(), and ForceOfHell.Scripts.MainCharacter.Player.HandleCollision().
healthActual
int ForceOfHell.Scripts.MainCharacter.Player.healthActual = health
Definition at line 35 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.HitAsync().
JumpVelocity
const float ForceOfHell.Scripts.MainCharacter.Player.JumpVelocity = -350.0f static
Definition at line 23 of file Player.cs.
manaActual
int ForceOfHell.Scripts.MainCharacter.Player.manaActual = mana
Definition at line 34 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess(), and ForceOfHell.Scripts.MainCharacter.Player.attack().
Speed
const float ForceOfHell.Scripts.MainCharacter.Player.Speed = 200.0f static
Definition at line 22 of file Player.cs.
WeaponOffsetLeft
const float ForceOfHell.Scripts.MainCharacter.Player.WeaponOffsetLeft = 0f static private
Definition at line 27 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection().
WeaponOffsetRight
const float ForceOfHell.Scripts.MainCharacter.Player.WeaponOffsetRight = 13f static private
Definition at line 28 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.UpdateSpriteDirection().
Property Documentation
CanClimb
bool ForceOfHell.Scripts.MainCharacter.Player.CanClimb get set
Definition at line 60 of file Player.cs.
CargarBullet
PackedScene ForceOfHell.Scripts.MainCharacter.Player.CargarBullet get set
Definition at line 43 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player.attack().
ClimbAnchorX
float ForceOfHell.Scripts.MainCharacter.Player.ClimbAnchorX get set
Ancla horizontal de la escalera actual.
Definition at line 63 of file Player.cs.
CoyoteTimeCounter
float ForceOfHell.Scripts.MainCharacter.Player.CoyoteTimeCounter get set
Tiempo restante para salto coyote (acceso público, modificación interna).
Definition at line 52 of file Player.cs.
IsDying
bool ForceOfHell.Scripts.MainCharacter.Player.IsDying get set
Indica si el jugador está en proceso de muerte.
Definition at line 59 of file Player.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Player._PhysicsProcess(), ForceOfHell.Scripts.MainCharacter.Player.Die(), and ForceOfHell.Scripts.MainCharacter.Player.SetAnimation().
The documentation for this class was generated from the following file:
Scripts/MainCharacter/Player.cs