ForceOfHell: ForceOfHell.Scripts.MainCharacter.Camera Class Reference
ForceOfHell.Scripts.MainCharacter.Camera Class Reference
Represents a 2D camera that follows the player and adjusts its position based on the player's movement.
Public Member Functions
override void _Ready ()
Método que se llama cuando el nodo está listo.
override void _Process (double delta)
Método que se llama en cada frame para actualizar la cámara.
Private Member Functions
void smoothingSpeed (double delta)
Método que se llama para suavizar la velocidad de la cámara.
void controlDrag ()
Controla el arrastre de la cámara según la velocidad del jugador.
Private Attributes
Player player
Exporta el nodo Player para acceder a sus propiedades.
float targetDragLeft = 0f
Velocidad de arrastre objetivo hacia la izquierda.
float targetDragRight = 0f
Velocidad de arrastre objetivo hacia la derecha.
float smoothSpeedHorizontal = 5f
Velocidad de suavizado horizontal.
float smoothSpeedVertical = 8f
Velocidad de suavizado vertical.
Detailed Description
Represents a 2D camera that follows the player and adjusts its position based on the player's movement.
This class inherits from Camera2D and provides functionality to smooth the camera's position based on the player's velocity. It includes methods for controlling drag and smoothing speed, which are called during the game loop.
Definition at line 11 of file Camera.cs.
Member Function Documentation
_Process()
override void ForceOfHell.Scripts.MainCharacter.Camera._Process (double delta)
Método que se llama en cada frame para actualizar la cámara.
Definition at line 50 of file Camera.cs.
References ForceOfHell.Scripts.MainCharacter.Camera.controlDrag(), and ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed().
_Ready()
override void ForceOfHell.Scripts.MainCharacter.Camera._Ready ()
Método que se llama cuando el nodo está listo.
Definition at line 41 of file Camera.cs.
References ForceOfHell.Scripts.MainCharacter.Camera.smoothSpeedHorizontal.
controlDrag()
void ForceOfHell.Scripts.MainCharacter.Camera.controlDrag () private
Controla el arrastre de la cámara según la velocidad del jugador.
Definition at line 76 of file Camera.cs.
References ForceOfHell.Scripts.MainCharacter.Camera.player, ForceOfHell.Scripts.MainCharacter.Camera.targetDragLeft, and ForceOfHell.Scripts.MainCharacter.Camera.targetDragRight.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera._Process().
smoothingSpeed()
void ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed (double delta) private
Método que se llama para suavizar la velocidad de la cámara.
Definition at line 60 of file Camera.cs.
References ForceOfHell.Scripts.MainCharacter.Camera.smoothSpeedHorizontal, ForceOfHell.Scripts.MainCharacter.Camera.smoothSpeedVertical, ForceOfHell.Scripts.MainCharacter.Camera.targetDragLeft, and ForceOfHell.Scripts.MainCharacter.Camera.targetDragRight.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera._Process().
Member Data Documentation
player
Player ForceOfHell.Scripts.MainCharacter.Camera.player private
Exporta el nodo Player para acceder a sus propiedades.
Definition at line 16 of file Camera.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera.controlDrag().
smoothSpeedHorizontal
float ForceOfHell.Scripts.MainCharacter.Camera.smoothSpeedHorizontal = 5f private
Velocidad de suavizado horizontal.
Definition at line 31 of file Camera.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera._Ready(), and ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed().
smoothSpeedVertical
float ForceOfHell.Scripts.MainCharacter.Camera.smoothSpeedVertical = 8f private
Velocidad de suavizado vertical.
Definition at line 36 of file Camera.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed().
targetDragLeft
float ForceOfHell.Scripts.MainCharacter.Camera.targetDragLeft = 0f private
Velocidad de arrastre objetivo hacia la izquierda.
Definition at line 21 of file Camera.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera.controlDrag(), and ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed().
targetDragRight
float ForceOfHell.Scripts.MainCharacter.Camera.targetDragRight = 0f private
Velocidad de arrastre objetivo hacia la derecha.
Definition at line 26 of file Camera.cs.
Referenced by ForceOfHell.Scripts.MainCharacter.Camera.controlDrag(), and ForceOfHell.Scripts.MainCharacter.Camera.smoothingSpeed().
The documentation for this class was generated from the following file:
Scripts/MainCharacter/Camera.cs