ForceOfHell: ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState Class Reference
ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState Class Reference
Represents the climbing movement state of the player, managing interactions and physics during climbing.
Public Member Functions
override async Task Ready ()
Prepares the main character for interaction by ensuring it is fully initialized and ready within the scene.
override void Enter ()
Sets the player's state to begin climbing by aligning the player with the ladder and preparing for vertical movement.
override void Update (double delta)
Updates the player's movement state based on the current conditions and player capabilities.
override void UpdatePhysics (double delta)
Updates the player's physics state during climbing, adjusting movement and animation based on input and climbing conditions.
override void HandleInput (InputEvent ev)
Handles input events to initiate a jump action when the appropriate conditions are met.
Public Member Functions inherited from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State
virtual void Exit ()
Se invoca cuando el estado termina (se sale de él).
Private Member Functions
void SnapToLadder ()
Aligns the player's horizontal position to the nearest climbing ladder anchor point to facilitate proper ladder interaction.
Private Attributes
PlayerType _player
Static Private Attributes
const float ClimbSpeed = 120f
Additional Inherited Members
Protected Attributes inherited from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State
MovementStateMachine stateMachine
Campo protegido mantenido por compatibilidad. Los estados existentes usan stateMachine.
Properties inherited from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State
MovementStateMachine StateMachine [get, set]
Propiedad pública para acceder a la máquina de estados. El setter es interno.
Detailed Description
Represents the climbing movement state of the player, managing interactions and physics during climbing.
This state handles the player's transition into climbing, updates movement based on input, and ensures proper alignment with climbing ladders. It also manages state transitions based on climbing conditions, such as initiating climbing, jumping, or returning to idle or running states.
Definition at line 14 of file ClimbMovementState.cs.
Member Function Documentation
Enter()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Enter () virtual
Sets the player's state to begin climbing by aligning the player with the ladder and preparing for vertical movement.
Call this method when the player interacts with a ladder to initiate climbing. The player's velocity is reset and their position is adjusted to ensure proper alignment with the ladder before movement begins.
Reimplemented from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.
Definition at line 40 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.SnapToLadder().
HandleInput()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.HandleInput (InputEvent ev) virtual
Handles input events to initiate a jump action when the appropriate conditions are met.
Transitions the player to the 'JumpingMovementState' if the jump action is pressed and neither the move up nor move down actions are active. This ensures that jumping only occurs when the player is not climbing.
Parameters
ev The input event containing information about the player's current actions. Must not be null.
Reimplemented from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.
Definition at line 113 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.stateMachine, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
Ready()
override async Task ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Ready () virtual
Prepares the main character for interaction by ensuring it is fully initialized and ready within the scene.
Call this method before attempting to interact with the main character to guarantee it is properly initialized. The method waits asynchronously if the main character node is not yet ready, ensuring safe access and interaction.
Returns
A task that completes when the main character node is ready for interaction.
Reimplemented from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.
Definition at line 26 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player.
SnapToLadder()
void ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.SnapToLadder () private
Aligns the player's horizontal position to the nearest climbing ladder anchor point to facilitate proper ladder interaction.
This method adjusts the player's global position to ensure they are correctly positioned for climbing. It is typically called when the player is near a ladder to enable smooth transitions onto the ladder.
Definition at line 131 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Enter(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.UpdatePhysics().
Update()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Update (double delta) virtual
Updates the player's movement state based on the current conditions and player capabilities.
If the player is not able to climb and is on the floor, the method transitions the state machine to either 'RunningMovementState' or 'IdleMovementState' based on the player's horizontal velocity.
Parameters
delta The time elapsed since the last update, used to calculate movement changes.
Reimplemented from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.
Definition at line 55 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player, ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.stateMachine, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.MovementStateMachine.TransitionTo().
UpdatePhysics()
override void ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.UpdatePhysics (double delta) virtual
Updates the player's physics state during climbing, adjusting movement and animation based on input and climbing conditions.
If climbing is not permitted, the player's velocity is reset and sliding occurs. When climbing is allowed, vertical movement is determined by input, and the appropriate climbing or idle animation is set based on movement. This method should be called once per physics frame to ensure responsive climbing behavior.
Parameters
delta The time elapsed since the last frame, in seconds. Used to calculate movement adjustments for smooth physics updates.
Reimplemented from ForceOfHell.Scripts.StateMachine.MovementStateMachine.State.
Definition at line 80 of file ClimbMovementState.cs.
References ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player, ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.ClimbSpeed, and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.SnapToLadder().
Member Data Documentation
_player
PlayerType ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState._player private
Definition at line 17 of file ClimbMovementState.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Enter(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Ready(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.SnapToLadder(), ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.Update(), and ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.UpdatePhysics().
ClimbSpeed
const float ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.ClimbSpeed = 120f static private
Definition at line 16 of file ClimbMovementState.cs.
Referenced by ForceOfHell.Scripts.StateMachine.MovementStateMachine.States.ClimbMovementState.UpdatePhysics().
The documentation for this class was generated from the following file:
Scripts/StateMachine/MovementStateMachine/States/ClimbMovementState.cs