ForceOfHell: ForceOfHell.Scripts.Weapons.Bullet.Bullet Class Reference
ForceOfHell.Scripts.Weapons.Bullet.Bullet Class Reference
Bala que se desplaza en una dirección fija y se destruye al chocar con el terreno.
Public Member Functions
override void _Ready ()
Inicializa la animación si existe.
override void _Process (double delta)
Mueve la bala cada frame.
void Configure (Vector2 direction, string animation, float damege)
Configura la dirección y la animación, y rota la bala según el movimiento.
Public Attributes
string animation = string.Empty
Nombre de la animación a reproducir.
float damage
Private Member Functions
void OnBodyEntered (Node body)
Elimina la bala al chocar con el terreno.
void OnAreaEntered (Area2D area)
Handles logic when another Area2D enters the monitored area.
void HandleCollision (Node node)
Handles a collision with the specified node, applying damage if applicable and removing the node from the scene.
Private Attributes
Vector2 _direction = Vector2.Zero
Dirección normalizada del movimiento.
AnimatedSprite2D _animatedSprite
Sprite animado de la bala.
CollisionShape2D _collisionShape
Forma de colisión de la bala.
Static Private Attributes
const float Speed = 450f
Velocidad lineal de la bala.
Detailed Description
Bala que se desplaza en una dirección fija y se destruye al chocar con el terreno.
Definition at line 10 of file Bullet.cs.
Member Function Documentation
_Process()
override void ForceOfHell.Scripts.Weapons.Bullet.Bullet._Process (double delta)
Mueve la bala cada frame.
Definition at line 37 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet._direction, and ForceOfHell.Scripts.Weapons.Bullet.Bullet.Speed.
_Ready()
override void ForceOfHell.Scripts.Weapons.Bullet.Bullet._Ready ()
Inicializa la animación si existe.
Definition at line 30 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet._animatedSprite, and ForceOfHell.Scripts.Weapons.Bullet.Bullet.animation.
Configure()
void ForceOfHell.Scripts.Weapons.Bullet.Bullet.Configure (Vector2 direction, string animation, float damege)
Configura la dirección y la animación, y rota la bala según el movimiento.
Definition at line 48 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet._direction, and ForceOfHell.Scripts.Weapons.Bullet.Bullet.animation.
HandleCollision()
void ForceOfHell.Scripts.Weapons.Bullet.Bullet.HandleCollision (Node node) private
Handles a collision with the specified node, applying damage if applicable and removing the node from the scene.
If the node belongs to the 'Terreno' group, it is immediately removed from the scene. For other node types, damage is applied before removal. The method ensures that the collision effects are handled according to the type of node encountered.
Parameters
node The node involved in the collision. This may represent terrain, boxes, Balrogs, Skeletons, or Goblins.
Definition at line 82 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet.damage.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet.OnAreaEntered(), and ForceOfHell.Scripts.Weapons.Bullet.Bullet.OnBodyEntered().
OnAreaEntered()
void ForceOfHell.Scripts.Weapons.Bullet.Bullet.OnAreaEntered (Area2D area) private
Handles logic when another Area2D enters the monitored area.
Parameters
area The Area2D instance that has entered the area. Cannot be null.
Definition at line 69 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet.HandleCollision().
OnBodyEntered()
void ForceOfHell.Scripts.Weapons.Bullet.Bullet.OnBodyEntered (Node body) private
Elimina la bala al chocar con el terreno.
Definition at line 60 of file Bullet.cs.
References ForceOfHell.Scripts.Weapons.Bullet.Bullet.HandleCollision().
Member Data Documentation
_animatedSprite
AnimatedSprite2D ForceOfHell.Scripts.Weapons.Bullet.Bullet._animatedSprite private
Sprite animado de la bala.
Definition at line 22 of file Bullet.cs.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet._Ready().
_collisionShape
CollisionShape2D ForceOfHell.Scripts.Weapons.Bullet.Bullet._collisionShape private
Forma de colisión de la bala.
Definition at line 25 of file Bullet.cs.
_direction
Vector2 ForceOfHell.Scripts.Weapons.Bullet.Bullet._direction = Vector2.Zero private
Dirección normalizada del movimiento.
Definition at line 16 of file Bullet.cs.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet._Process(), and ForceOfHell.Scripts.Weapons.Bullet.Bullet.Configure().
animation
string ForceOfHell.Scripts.Weapons.Bullet.Bullet.animation = string.Empty
Nombre de la animación a reproducir.
Definition at line 19 of file Bullet.cs.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet._Ready(), and ForceOfHell.Scripts.Weapons.Bullet.Bullet.Configure().
damage
float ForceOfHell.Scripts.Weapons.Bullet.Bullet.damage
Definition at line 27 of file Bullet.cs.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet.HandleCollision().
Speed
const float ForceOfHell.Scripts.Weapons.Bullet.Bullet.Speed = 450f static private
Velocidad lineal de la bala.
Definition at line 13 of file Bullet.cs.
Referenced by ForceOfHell.Scripts.Weapons.Bullet.Bullet._Process().
The documentation for this class was generated from the following file:
Scripts/Weapons/Bullet/Bullet.cs