ForceOfHell: ForceOfHell.Scripts.Weapons.ReadWeapons Class Reference
ForceOfHell.Scripts.Weapons.ReadWeapons Class Reference
Nodo responsable de cargar las definiciones de armas desde un CSV y exponerlas al resto del juego. Se asegura de leer el archivo una sola vez durante la sesión.
Static Public Member Functions
static bool TryGetWeapon (int id, out Weapons weapon)
Devuelve un arma específica si existe en el diccionario.
Properties
static IReadOnlyDictionary< int, Weapons > Weapons [get]
Vista de solo lectura del diccionario para evitar escrituras externas.
Static Private Member Functions
static ReadWeapons ()
static void LoadWeaponsFromCsv ()
Lee el archivo CSV completo, parsea cada línea y popula el diccionario de armas.
static ? string NormalizeNull (string value)
Normaliza valores vacíos o con la palabra "null" a null real para evitar cadenas sin contenido.
static string[] SplitCsv (string line)
Divide una línea CSV respetando comillas dobles para campos con comas internas.
Static Private Attributes
const string FilePath = "res://Files/Weapon/weapons.csv"
Ruta al CSV dentro del sistema de archivos virtual de Godot (res://).
static Dictionary< int, Weapons > WeaponsById = new()
Diccionario con todas las armas, indexadas por su identificador único.
Detailed Description
Nodo responsable de cargar las definiciones de armas desde un CSV y exponerlas al resto del juego. Se asegura de leer el archivo una sola vez durante la sesión.
Definition at line 13 of file ReadWeapons.cs.
Constructor & Destructor Documentation
ReadWeapons()
static ForceOfHell.Scripts.Weapons.ReadWeapons.ReadWeapons () static private
Definition at line 30 of file ReadWeapons.cs.
References ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv(), and ForceOfHell.Scripts.Weapons.ReadWeapons.WeaponsById.
Member Function Documentation
LoadWeaponsFromCsv()
static void ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv () static private
Lee el archivo CSV completo, parsea cada línea y popula el diccionario de armas.
Definition at line 51 of file ReadWeapons.cs.
References ForceOfHell.Scripts.Weapons.ReadWeapons.FilePath, ForceOfHell.Scripts.Weapons.ReadWeapons.NormalizeNull(), ForceOfHell.Scripts.Weapons.ReadWeapons.SplitCsv(), and ForceOfHell.Scripts.Weapons.ReadWeapons.WeaponsById.
Referenced by ForceOfHell.Scripts.Weapons.ReadWeapons.ReadWeapons().
NormalizeNull()
static ? string ForceOfHell.Scripts.Weapons.ReadWeapons.NormalizeNull (string value) static private
Normaliza valores vacíos o con la palabra "null" a null real para evitar cadenas sin contenido.
Definition at line 125 of file ReadWeapons.cs.
Referenced by ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv().
SplitCsv()
static string[] ForceOfHell.Scripts.Weapons.ReadWeapons.SplitCsv (string line) static private
Divide una línea CSV respetando comillas dobles para campos con comas internas.
Definition at line 134 of file ReadWeapons.cs.
Referenced by ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv().
TryGetWeapon()
static bool ForceOfHell.Scripts.Weapons.ReadWeapons.TryGetWeapon (int id, out Weapons weapon) static
Devuelve un arma específica si existe en el diccionario.
Member Data Documentation
FilePath
const string ForceOfHell.Scripts.Weapons.ReadWeapons.FilePath = "res://Files/Weapon/weapons.csv" static private
Ruta al CSV dentro del sistema de archivos virtual de Godot (res://).
Definition at line 18 of file ReadWeapons.cs.
Referenced by ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv().
WeaponsById
Dictionary<int, Weapons> ForceOfHell.Scripts.Weapons.ReadWeapons.WeaponsById = new() static private
Diccionario con todas las armas, indexadas por su identificador único.
Definition at line 23 of file ReadWeapons.cs.
Referenced by ForceOfHell.Scripts.Weapons.ReadWeapons.LoadWeaponsFromCsv(), and ForceOfHell.Scripts.Weapons.ReadWeapons.ReadWeapons().
Property Documentation
Weapons
IReadOnlyDictionary<int, Weapons> ForceOfHell.Scripts.Weapons.ReadWeapons.Weapons static get
Vista de solo lectura del diccionario para evitar escrituras externas.
Definition at line 28 of file ReadWeapons.cs.
Referenced by ForceOfHell.Scripts.Weapons.DropWeapon.AssignRandomWeapon(), and ForceOfHell.Scripts.Weapons.Weapons.SetWeapon().
The documentation for this class was generated from the following file:
Scripts/Weapons/ReadWeapons.cs