ForceOfHell: ForceOfHell.Scripts.Objects.Box Class Reference
ForceOfHell.Scripts.Objects.Box Class Reference
Represents a destructible box in the game world that can take damage and drop items upon destruction.
Public Member Functions
override void _Process (double delta)
Called every frame to update the node's state. Handles destruction logic when the box's health reaches zero or below.
void TakeDamage (bool IsMelee)
Applies damage to the box, reducing its health based on the type of attack.
Public Attributes
AnimatedSprite2D _animatedSprite2D
CollisionShape2D _collisionShape2D
first_level _firstLevel
Private Member Functions
void RandomizeDrop ()
Randomly generates and drops an item at the current position based on predefined probabilities.
Private Attributes
int boxHealth = 4
bool _isDestroyed
Detailed Description
Represents a destructible box in the game world that can take damage and drop items upon destruction.
The Box class inherits from RigidBody2D and manages its own health and destruction state. When the box's health reaches zero, it triggers an item drop based on predefined probabilities and removes itself from the scene. This class is intended for use in scenarios where interactive, destructible objects are needed, such as breakable containers or obstacles. Item drops are delegated to the first level, and the box is freed after attempting to drop an item.
Definition at line 15 of file Box.cs.
Member Function Documentation
_Process()
override void ForceOfHell.Scripts.Objects.Box._Process (double delta)
Called every frame to update the node's state. Handles destruction logic when the box's health reaches zero or below.
This method is typically called by the engine once per frame. Override this method to implement per-frame logic for the node.
Parameters
delta The elapsed time, in seconds, since the previous frame. Used to synchronize updates with the frame rate.
Definition at line 31 of file Box.cs.
References ForceOfHell.Scripts.Objects.Box._animatedSprite2D, ForceOfHell.Scripts.Objects.Box._isDestroyed, ForceOfHell.Scripts.Objects.Box.boxHealth, and ForceOfHell.Scripts.Objects.Box.RandomizeDrop().
RandomizeDrop()
void ForceOfHell.Scripts.Objects.Box.RandomizeDrop () private
Randomly generates and drops an item at the current position based on predefined probabilities.
This method selects an item type to drop using random chance and delegates item creation to the first level. The method frees the current object after attempting to drop an item. If the current scene is not available, no item is dropped and the object is freed immediately.
Definition at line 61 of file Box.cs.
References ForceOfHell.Scripts.Objects.Box._firstLevel, and ForceOfHell.Scripts.FirstLevel.first_level.GenerateItem().
Referenced by ForceOfHell.Scripts.Objects.Box._Process().
TakeDamage()
void ForceOfHell.Scripts.Objects.Box.TakeDamage (bool IsMelee)
Applies damage to the box, reducing its health based on the type of attack.
Parameters
IsMelee true to apply melee damage, which reduces health by 2; false to apply non-melee damage, which reduces health by 1.
Definition at line 45 of file Box.cs.
References ForceOfHell.Scripts.Objects.Box.boxHealth.
Member Data Documentation
_animatedSprite2D
AnimatedSprite2D ForceOfHell.Scripts.Objects.Box._animatedSprite2D
Definition at line 17 of file Box.cs.
Referenced by ForceOfHell.Scripts.Objects.Box._Process().
_collisionShape2D
CollisionShape2D ForceOfHell.Scripts.Objects.Box._collisionShape2D
Definition at line 18 of file Box.cs.
_firstLevel
first_level ForceOfHell.Scripts.Objects.Box._firstLevel
Definition at line 19 of file Box.cs.
Referenced by ForceOfHell.Scripts.Objects.Box.RandomizeDrop().
_isDestroyed
bool ForceOfHell.Scripts.Objects.Box._isDestroyed private
Definition at line 22 of file Box.cs.
Referenced by ForceOfHell.Scripts.Objects.Box._Process().
boxHealth
int ForceOfHell.Scripts.Objects.Box.boxHealth = 4 private
Definition at line 21 of file Box.cs.
Referenced by ForceOfHell.Scripts.Objects.Box._Process(), and ForceOfHell.Scripts.Objects.Box.TakeDamage().
The documentation for this class was generated from the following file:
Scripts/Objects/Box.cs